root: true
parser: esprima
parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    globalReturn: false
    impliedStrict: true
    experimentalObjectRestSpread: true
    jsx: true
env:
  browser: true
  node: true
  commonjs: true
  es6: true
  worker: true
  serviceworker: true
rules:
  # About Errors
  no-await-in-loop: error
  no-compare-neg-zero: error
  no-cond-assign:
    - error
    - always
  no-constant-condition: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-empty:
    - error
    -
      allowEmptyCatch: false
  no-empty-character-class: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-parens:
    - error
    - all
  no-func-assign: error
  no-inner-declarations:
    - error
    - both
  no-invalid-regexp:
    - error
    -
      allowConstructorFlags:
        - u
        - y
  no-irregular-whitespace:
    - error
    -
      skipStrings: true
      skipComments: true
      skipRegExps: true
      skipTemplates: true
  no-obj-calls: error
  no-prototype-builtins: error
  no-regex-spaces: error
  no-sparse-arrays: error
  no-template-curly-in-string: error
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  use-isnan: error
  valid-typeof: error

  # About Best Practices
  accessor-pairs:
    - error
    -
      setWithoutGet: true
      getWithoutSet: false
  array-callback-return: error
  block-scoped-var: error
  class-methods-use-this: error
  complexity: error
  consistent-return: error
  curly: error
  default-case: error
  dot-location:
    - error
    - property
  dot-notation: error
  eqeqeq: error
  guard-for-in: error
  no-alert: error
  no-caller: error
  no-case-declarations: error
  no-div-regex: error
  no-else-return: error
  no-empty-function:
    - error
    -
      allow:
        - constructors
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-fallthrough: error
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal: error
  no-octal-escape: error
  no-param-reassign:
    - error
    -
      props: true
  no-proto: error
  no-redeclare: error
  no-return-assign:
    - error
    - always
  no-return-await: error
  no-script-url: error
  no-self-assign:
    - error
    -
      props: true
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions:
    - error
    -
      allowShortCircuit: true
      allowTernary: true
      allowTaggedTemplates: true
  no-unused-labels: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-useless-return: error
  no-void: error
  no-warning-comments: warn
  no-with: error
  prefer-promise-reject-errors:
    - error
    -
      allowEmptyReject: true
  radix: error
  require-await: error
  wrap-iife:
    - error
    - inside
    -
      functionPrototypeMethods: true
  yoda: error

  # About Variables
  no-delete-var: error
  no-label-var: error
  no-restricted-globals:
    - error
    - event
  no-shadow-restricted-names: error
  no-undef:
    - error
    -
      typeof: true
  no-undef-init: error
  no-unused-vars:
    - error
    -
      ignoreRestSiblings: true
  no-use-before-define:
    - error
    - nofunc

  # About Node.js and CommonJS
  handle-callback-err:
    - error
    - ^(err|error)$
  no-mixed-requires:
    - error
    -
      grouping: true
      allowCall: true
  no-new-require: error
  no-path-concat: error

  # About Stylistic
  array-bracket-spacing:
    - error
    - never
  block-spacing:
    - error
    - always
  brace-style:
    - error
    - 1tbs
    -
      allowSingleLine: true
  camelcase: error
  capitalized-comments:
    - error
    - always
    -
      ignorePattern: pragma|ignore
      ignoreInlineComments: true
      ignoreConsecutiveComments: true
  comma-dangle: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  eol-last: error
  func-call-spacing: error
  func-name-matching: error
  func-names:
    - error
    - never
  indent:
    - error
    - tab
    -
      SwitchCase: 1
      FunctionDeclaration:
        parameters: 1
      FunctionExpression:
        parameters: 1
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  linebreak-style: warn
  max-depth: warn
  max-len:
    - warn
    -
      tabWidth: 2
      ignoreComments: true
      ignoreUrls: true
      ignoreTemplateLiterals: true
  max-nested-callbacks:
    - warn
    - 4
  max-params:
    - warn
    - 4
  max-statements-per-line: error
  new-cap: error
  new-parens: error
  newline-after-var: warn
  newline-before-return: warn
  no-array-constructor: error
  no-lonely-if: error
  no-mixed-operators: error
  no-mixed-spaces-and-tabs: error
  no-multi-assign: error
  no-multiple-empty-lines:
    - error
    -
      max: 1
  no-negated-condition: error
  no-new-object: error
  no-restricted-syntax:
    - error
    - WithStatement
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-property-newline: error
  one-var: error
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak:
    - error
    - after
    -
      overrides:
        '?': before
        ':': before
  padded-blocks:
    - error
    - never
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
    -
      avoidEscape: true
      allowTemplateLiterals: true
  semi: error
  semi-spacing: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - always
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops:
    - error
    -
      words: true
      nonwords: false
  spaced-comment:
    - error
    - always
    -
      line:
        exceptions:
          - '-'
      block:
        markers:
          - '!'
        balanced: true
  template-tag-spacing: error
  unicode-bom: error

  # About ES6
  arrow-parens:
    - warn
    - as-needed
  arrow-spacing: error
  constructor-super: error
  generator-star-spacing:
    - error
    - both
  no-class-assign: error
  no-const-assign: error
  no-dupe-class-members: error
  no-new-symbol: error
  no-this-before-super: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  prefer-const: error
  prefer-destructuring: warn
  prefer-rest-params: warn
  prefer-template: warn
  require-yield: error
  rest-spread-spacing: error
  symbol-description: error
  template-curly-spacing: error
  yield-star-spacing:
    - error
    - both
